#version: '3.8'

services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: api_users_php
        volumes:
            - ./:/var/www/html
        depends_on:
            - mysql
        networks:
            - api_users_network
#        environment:
#            MYSQL_ROOT_PASSWORD: root
#            MYSQL_DATABASE: symfony
#            MYSQL_USER: symfony_user
#            MYSQL_PASSWORD: symfony_pass

    nginx:
        image: nginx:alpine
        container_name: api_users_nginx
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - api_users_network

    mysql:
        image: mysql:8.0
        container_name: api_users_mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony_user
            MYSQL_PASSWORD: symfony_pass
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - api_users_network

volumes:
    mysql_data:

networks:
    api_users_network:
        driver: bridge
